name: Generate Badges

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv lock
          uv sync
      
      - name: Create output directories
        run: |
          mkdir -p .out .html/badges
      
      - name: Generate badges
        run: |
          source .venv/bin/activate
          uv run make badges
      
      - name: Upload badges
        uses: actions/upload-artifact@v4
        with:
          name: badges
          path: .html/badges/
      
      - name: Deploy badges to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .html
          force_orphan: true