name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv lock
          uv sync
      
      - name: Check code style
        run: |
          source .venv/bin/activate
          uv run make check
      
      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          uv run make coverage
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .out/test_results.xml
      
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: .out/coverage.xml